---
stages: [check-pr]

check-pr:
  # Check the current commit message for compliance with commitizen
  stage: check-pr
  image: alpine:latest
  inherit:
    variables: false
  script:
    - apk add --no-cache --upgrade py3-pip
    - pip install -U commitizen
    - cz check --message "$CI_COMMIT_MESSAGE" >/tmp/cz_check || true # why does it return 1 if its actually 0?
    - grep "successful" /tmp/cz_check # ugly hack to workaround the above issue
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
